### ISSUE TITLE
NSKeyedUnarchiver - can be used to unarchive any bplist00 format data?

### ISSUE THREAD

**Issue by hagen** [magicien/JSceneKit#1]
Am trying to decode a bplist containing PDF data.
Top of the file looks like this:
```
bplist00ÔT$topX$objectsX$versionY$archiverÑTroot¢	
U$nullO\[%PDF-1.3
%Äåòåë§ó ÐÄÆ
4 0 obj
<< /Length 5 0 R /Filter /FlateDecode >>
```
NSKeyedUnarchiver would be used on Mac, but in Node, I am trying with this class. Object is not being decoded by the class. I know this is not the purpose of JSceneKit, but any suggestions would be helpful!

**Comment by magicien** [comment]
Hi, Hagen! Sorry for the late reply.
Basically, NSKeyedUnarchiver.js can unarchive any bplist00 file, but you have to implement classes which are archived in the file.

You can use `plutil -p bplistfile.bin` command to check which classes are archived in the file.
Output looks like;

> {
>   "$archiver" => "NSKeyedArchiver"
>   "$objects" => [
>     0 => "$null"
>     ...
>     3 => {
>       "$classes" => [
>         0 => "SCNPhysicsWorld"
>         1 => "NSObject"
>       ]
>       "$classname" => "SCNPhysicsWorld"
>     }
>     ...
>         365 => {
>       "$classes" => [
>         0 => "SCNScene"
>         1 => "NSObject"
>       ]
>       "$classname" => "SCNScene"
>     }
>   ]
>   "$top" => {
>     "root" => <CFKeyedArchiverUID 0x7fcbec500c00 [0x7fffb19e0570]>{value = 1}
>   }
>   "$version" => 100000
> }

And you have to implement classes for all "$classes".
If all classes have been already implemented, you can just use `NSKeyedUnarchiver.unarchiveObjectWithData(data)`.

**Comment by hagen** [comment]
I see! Thank you for clarifying. There are a lot of classes that haven't been implemented (as it's not specific to graphics), but I do understand how I'd go about leveraging JSceneKit for my project. Thanks

**Comment by yener35** [comment]
****

**Comment by FckYrShit56** [comment]
```

```

**Comment by 8063951087** [comment]
bplist00Ô
X$versionY$archiverT$topX$objects† _NSKeyedArchiverÑ	Troot€¢U$null_Shttps://1drv.ms/u/c/6bcf6d0757e941af/Ea9B6VcHbc8ggGt1AAAAAAABYs2r_lUQAuKuOp_ySdfG_g$)27ILQSV\
²

**Comment by 8063951087** [comment]
> bplist00Ô������� X$versionY$archiverT$topX$objects���† _��NSKeyedArchiverÑ� Troot€�¢�U$null_�Shttps://1drv.ms/u/c/6bcf6d0757e941af/Ea9B6VcHbc8ggGt1AAAAAAABYs2r_lUQAuKuOp_ySdfG_g���$)27ILQSV\��������������� ���������������²

**Comment by 8063951087** [comment]
[DPF-Assessment-Criteria-07072023.pdf](https://github.com/user-attachments/files/19659777/DPF-Assessment-Criteria-07072023.pdf)[](url)

**Comment by itsesme18-sketch** [comment]
* Returns the class object for the receiverâs superclass.
     * @access public
     * @returns {?Object} - 
     * @see https://developer.apple.com/documentation/objectivec/nsobject/1418803-superclass
     */

**Comment by itsesme18-sketch** [comment]
module.exports =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 127);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


//import CGPoint from '../CoreGraphics/CGPoint'
//import CGRect from '../CoreGraphics/CGRect'

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _ClassList2 = __webpack_require__(40);

var _ClassList3 = _interopRequireDefault(_ClassList2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError

**Comment by luzykdima-code** [comment]
bplist00Ô�������T$topX$objectsX$versionY$archiverÑ��Troot��¢	
U$nullO�\[%PDF-1.3
%Äåòåë§ó ÐÄÆ
4 0 obj
<< /Length 5 0 R /Filter /FlateDecode >>
